# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08796ad95549a7744ac9d29e33c110fc6e65b9572970bb7253d095e10cda06378c11c8f1848c81a95b5ef974c37742c1810bfb30b59b59f6f47e7570fb360590

test:
  secret_key_base: 8b3db9a5834099d558d084ba32023cc303f98e4d82ca26bf48635025c0abf06620b97ccf64cfc897334377022d669379f0e54faab805e615171964107d599d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
